### ISSUE TITLE
Hessian information needed when using user-registered functions in JuMP

### ISSUE THREAD

**Issue by mzagorowska** [MadNLP/MadNLP.jl#115]
As described here: https://discourse.julialang.org/t/unsupported-feature-hess-with-user-defined-functions-using-jump-and-alpine/70204/2

**Comment by sshin23** [comment]
Hi @mzagorowska, sorry for the late response.

MadNLP currently only supports a second-order algorithm, which requires Hessian info. The current issue with user-registered functions in JuMP is that JuMP does not provide Hessian info for the user-registered functions. As such, we don't have a method to query the necessary information. We're planning to support the quasi-Newton method, which doesn't require Hessian, but we don't have a concrete timeline yet (see #39). 

Closing in favor of #39
