### ISSUE TITLE
Question: Extension for cuSolver

### ISSUE THREAD

**Issue by amirmm11** [MadNLP/MadNLP.jl#271]
What extension can be added for cuSolver, I can't find it [here](https://juliahub.com/ui/Search?q=madnlp&type=packages).

The following codes, 

```julia
model = Model(()->MadNLP.Optimizer(linear_solver=CuMadNLPSolver))
@variable(model, x >= 0)
@variable(model, 0 <= y <= 3)
@NLobjective(model, Min, 12x + 20y)
@constraint(model, c1, 6x + 8y >= 100)
@constraint(model, c2, 7x + 12y >= 120)
optimize!(model)
```

gives me this error:

```
ERROR: MethodError: Cannot `convert` an object of type 
  typeof(CuMadNLPSolver) to an object of type 
  Type
```

**Comment by sshin23** [comment]
Hi @amirmm11, what's the goal here? If the goal is using GPU, you can try `linear_solver=LapackGPUSolver`

**Comment by amirmm11** [comment]
@sshin23 Yes, my goal is to use GPUT, I tried `linear_solver=LapackGPUSolver` but I want to see the performance when I use `cuSolver`.

**Comment by sshin23** [comment]
It uses a dense linear solver, so if you have a large-scale problem, it is likely to get into a memory issue.

Could you explain a bit more about the context of your problem? Currently, MadNLP only supports dense problems on GPU, but sparse methods on GPU are currently under development.

**Comment by amirmm11** [comment]
Sure, I am solving a stochastic optimization UC, and it is very sparse, but I thought you have a similar implementation as https://gitlab.pnnl.gov/exasgd/solvers/hykkt to include sparsity.

**Comment by sshin23** [comment]
@frapac's [Argos.jl](https://github.com/exanauts/Argos.jl) has some capability, but it is based on a reduction algorithm and uses a certain block structure in the problem. At this point, MadNLP can't solve general sparse NLPs, but the next release will likely support dealing with some sparse problems (but with a lot of caveats)
