### ISSUE TITLE
Support `MOI.ScalarNonlinearFunction`

### ISSUE THREAD

**Issue by pulsipher** [MadNLP/MadNLP.jl#279]
MOI's new interface removes the need to use `NL` macros in JuMP and has a number of other benefits. This new interface requires that you support `MOI.ScalarNonlinearFunction` and possibly `MOI.VectorNonlinearFunction`. This will be needed for InfiniteOpt to be compatible with MadNLP.

The updates to Ipopt.jl and Knitro.jl might be a useful guide.

**Comment by pulsipher** [comment]
Here is how Ipopt.jl was updated: https://github.com/jump-dev/Ipopt.jl/pull/346

**Comment by frapac** [comment]
Solved by #280
