### ISSUE TITLE
CuCholeskySolver GPU memory leak

### ISSUE THREAD

**Issue by KSepetanc** [MadNLP/MadNLP.jl#334]
I found out that solving the ExaModels AC OPF documentation example in a loop results in possible memory leak. All of 6 GB of GPU's VRAM is taken in about 33 solves.

Below is part relevant part of the code and full code to reproduce can be downloaded: [gpu memory leak.zip](https://github.com/MadNLP/MadNLP.jl/files/15093658/gpu.memory.leak.zip)

```
m = ac_power_model("pglib_opf_case13659_pegase.m",backend=CUDABackend())

for i in 1:50
    println(i)
    madnlp(m,linear_solver=MadNLPGPU.CuCholeskySolver)
end
```

Configuration:
Windows,
CPU: AMD R9 5950x
GPU GTX 1060 6GB

**Comment by sshin23** [comment]
GPU memory usage is not necessarily optimized on MadNLP. Curious if this is CuCholeskySolver's issue or general MadNLP issue. Have you tried `CUDSSSolver` (the default solver for CUDA)?

**Comment by KSepetanc** [comment]
I have tried, but it fails with an error reported in [334](https://github.com/MadNLP/MadNLP.jl/issues/334).

I can report there is much less severe memory issue running on Linux, but still existent.

**Comment by KSepetanc** [comment]
With package update as suggested in 333 issue, I've managed to run OPF with `CUDSSSolver`.
I the memory issue is still present. Memory usage goes slowly up with repeated runs of MadNLP until failure due to full VRAM.
