### ISSUE TITLE
Parameterizing `Solver` as `Solver{T}`

### ISSUE THREAD

**Issue by sshin23** [MadNLP/MadNLP.jl#72]
This change will allow running MadNLP with different precisions (as long as compatible derivative callbacks and linear solvers exist).

**Comment by frapac** [comment]
That's a good idea. I think it could also help on the GPU. Also: are you mentioning the linear solvers or the interior point solvers?

I would also suggest to use a different naming between the interior point solver (`IPMSolver{KKT}`?) and the linear solvers (`LinearSolvers{T}`?).

**Comment by sshin23** [comment]
@frapac yes, I think we need some consistent naming convention. Maybe we can do the following.
`Solver <: AbstractInteriorPointSolver` -> `InteriorPointSolver{T} <: AbstractInteriorPointSolver{T}`
`MadNLPMa27.Solver <: AbstractLinearSolver` -> `Ma27Solver{T} <: AbstractLinearSolver{T}`

Also, now that we aiming to make everything run on GPU, maybe we need to add one more signature and make something like `InteriorPointSovler{T,V{T}}`, so that we can support both `InteriorPointSovler{Float64,Vector{Float64}}` and `InteriorPonitSolver{Float64,CuVector{Float64}}`. How does that sound?

**Comment by sshin23** [comment]
I think what I wrote might be a bit outdated, but you know what I'm saying 🤣

**Comment by frapac** [comment]
Closing this issue as it is deprecated.
